### ISSUE TITLE
`export` makes the joblist panel become empty

### ISSUE THREAD

**Issue by ian-from-dover** [AY2122S2-CS2103T-T11-4/tp#122]
Should explain to user that this is not a bug, that the joblist will show all the jobs assigned to the exported person

**Comment by zhongfu** [comment]
@ian-from-dover is this a bug or a documentation (e.g. in-app warning, or UG) issue?

**Comment by ian-from-dover** [comment]
@zhongfu in-app prompt about it should be good enough. prompt them to do the list command again

**Comment by ian-from-dover** [comment]
Moved to https://github.com/AY2122S2-CS2103T-T11-4/tp/issues/219 to be addressed with the other UG bugs.
