### ISSUE TITLE
Improvements to implementation of `Payment` and `JobMarkCommand`

### ISSUE THREAD

**Issue by Spyobird** [AY2122S2-CS2103T-T11-4/tp#129]
Current implementation avoids the issue where user can `assign`, `mark`, `un-assign` by editing the data file and `(un)mark`. This results in unwanted `Payment` instances being left in the un-assigned `Person`s.

However, by avoiding that issue, it introduces the new (minor) issue that the user can call `(un)mark` on `Job`s not assigned to any `Person`, which is actually not a problem at all. Just that `mark` would create an error in that case.

`(un)mark` refers to the second state of the `mark` command which un-marks the `Job`.

Technically changes are in #128 and have not been merged.

**Comment by zhongfu** [comment]
is this still an issue? does it require additional documentation?

**Comment by Spyobird** [comment]
No
