### ISSUE TITLE
Ellipsis with `ResultDisplay` in UI

### ISSUE THREAD

**Issue by Spyobird** [AY2122S2-CS2103T-T11-4/tp#131]
Seems to only show 3 lines, also sometimes ellipsis appear probably when the extra lines get truncated off.

![ui_bug2](https://user-images.githubusercontent.com/4799598/161127495-cafa576f-2385-4311-a366-289f3b780993.PNG)

**Comment by ian-from-dover** [comment]
It is like that by design. I will edit all command messages to fit within 3 lines and put them all into `Messages.java` for 1.4
