### ISSUE TITLE
Allow `assign` to update `Payment`s associated with marked `Job`s

### ISSUE THREAD

**Issue by Spyobird** [AY2122S2-CS2103T-T11-4/tp#137]
See #134.

**Comment by ian-from-dover** [comment]
Basically 

Steps to reproduce

mark job
assign job to new person
new person's $unpaid does not update
Elliots suggested fix:

make it such that you can't assign a marked job

**Comment by ian-from-dover** [comment]
We now cant assign a marked job. So users can't get to this issue

**Comment by zhongfu** [comment]
@ian-from-dover do we close this, or does this require documentation?

**Comment by ian-from-dover** [comment]
Addressed by #219
