### ISSUE TITLE
[PE-D] Invalid phone input but still able to successfully add/edit person 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-4/tp#146]
**Describe the bug**

After adding an invalid phone field, the add/edit command is still successful. 

**To Reproduce**

1. Type "add OR edit n/name p/912 e/goij@gmail.com a/1 r/80"
2. Successfully adds/edits new person even thought phone field is invalid

**Expected behaviour**

Show error message to indicate invalid phone field. 

**Screenshots**

![Screenshot 2022-04-01 at 2.14.05 PM.png](https://raw.githubusercontent.com/sophiien/ped/main/files/ebcc46da-f08f-42b1-a26d-12ff9b621749.png)

**Desktop (please complete the following information):**

OS: macOS 11.6

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: sophiien/ped#1

**Comment by zhongfu** [comment]
er, these are not necessarily invalid phone numbers, are they?

**Comment by zhongfu** [comment]
shortest subscriber phone numbers seem to be for St Helena and Tokelau (iirc?), which both have 5-digit phone numbers for normal subscribers (was 4, but they migrated)

we can either let this be (and claim that we're allowing for extra flexibility for users), or add a reasonable number limit:
- shortest possible number?
- 8 digits for Singapore? (but what if the user isn't from Singapore, or some other country with 8-digit numbers)

I reckon it should be safe enough to leave it as is, and dispute any bugs arising from this

**Comment by ian-from-dover** [comment]
999 is a valid phone number

**Comment by zhongfu** [comment]
or rather, we should just let users have the flexibility of having shorter phone numbers (e.g. they might have a private phone network, you never know)
