### ISSUE TITLE
[PE-D] Add a job documentation does not match what can be done

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-4/tp#178]
![image.png](https://raw.githubusercontent.com/ngjunkang/ped/main/files/9c9eaae7-a64f-4a42-8548-42b5f4b5ef45.png)

The format is correct but the description and example are not standardised.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ngjunkang/ped#7

**Comment by zhongfu** [comment]
dupe of #151
