### ISSUE TITLE
[PE-D] Mark and Assign Feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-4/tp#180]
Hard to understand - perhaps assign feature could be talked about first since you need to do that in order to 'mark' 

![Screenshot 2022-04-01 at 2.58.36 PM.png](https://raw.githubusercontent.com/shurvirarora/ped/main/files/d5689a78-c322-4cf6-8a23-e78d09436c36.png)Screenshot 2022-04-01 at 2.58.36 PM

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: shurvirarora/ped#9

**Comment by zhongfu** [comment]
uhh... yeah i guess, can't hurt
