### ISSUE TITLE
[PE-D] Hyperlink on 'marked' does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-4/tp#183]
![image.png](https://raw.githubusercontent.com/ngjunkang/ped/main/files/10beea55-9fa8-4b15-bb53-79c512bb5e1f.png)

The hyperlink should bring me to where the section of mark is.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ngjunkang/ped#8

**Comment by zhongfu** [comment]
duplicate of #152
