### ISSUE TITLE
[PE-D] Jobs of the same name can be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-4/tp#187]
It may be confusing for HR manager to manage high number of jobs with the same name.

![image.png](https://raw.githubusercontent.com/ngjunkang/ped/main/files/f99871c3-48a9-4d87-9650-78f9f8b9625d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ngjunkang/ped#10

**Comment by ian-from-dover** [comment]
compare all the non-payment fields for duplicates when adding

**Comment by ovidharshini** [comment]
As Ian mentioned above, this is arguably not necessarily a feature flaw. Instead of updating the codebase to prevent duplicate job names from being added, I'm thinking of updating the guides to briefly explain the rationale behind this. Thoughts?

**Comment by ian-from-dover** [comment]
@ovidharshini I support this decision

**Comment by ian-from-dover** [comment]
Moved to #219 to be addressed with other minor UG bug-fixes
