### ISSUE TITLE
[PE-D] Unknown field in job list: In charge

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-4/tp#188]
![image.png](https://raw.githubusercontent.com/ngjunkang/ped/main/files/a367a8f9-df9c-4d0e-9d56-92cacd5b1d94.png)

I don't think the column "In charge" is used in any way.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: ngjunkang/ped#11

**Comment by Spyobird** [comment]
Similar to #176
