### ISSUE TITLE
[PE-D] Unreadable number of hours in job list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-4/tp#193]
![image.png](https://raw.githubusercontent.com/ngjunkang/ped/main/files/413eb7ad-c354-4b4f-b00a-93a439e9c62b.png)

Steps:
1. command: `job n/aa d/999999999999999999999999999999999999`

Expected: it should be still in hours, or handled in some way.

Seems that the max hour is 256...215, causing the unpaid amount to reflect wrongly.
 
![image.png](https://raw.githubusercontent.com/ngjunkang/ped/main/files/9019429c-c53d-4cbd-a7cf-2c73931ddefa.png)

On a side note, what is PT?? Part-time?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ngjunkang/ped#16

**Comment by Spyobird** [comment]
Need to fix string of `Duration` since it is using Java output. Also perhaps setting limits or string wrapping/scrolling would work

**Comment by ian-from-dover** [comment]
We mention a limit in the UG

**Comment by Spyobird** [comment]
Shouldn't be too tough to add a fix too, considering people in our PE are going to try to break stuff

**Comment by ian-from-dover** [comment]
Will be fixed when we enforce the duration and rate limit.
