### ISSUE TITLE
Adopt UG Best Practices to get A

### ISSUE THREAD

**Issue by ian-from-dover** [AY2122S2-CS2103T-T11-4/tp#203]
The examples are taken from last sem's UGs. Remember to credit them at the bottom of the UG

note: if we emulate [TuitionAddressBook](https://ay2122s1-cs2103t-f13-3.github.io/tp/UserGuide.html) we are guaranteed to get an A for UG.

- [x] Have a [`1.1 Welcome to PeopleSoft`](https://ay2122s2-cs2103t-w14-1.github.io/tp/UserGuide.html) section
- [x] Adopt the beautiful `1.2 How to Read This Guide` table from [TuitionAddressBook](https://ay2122s1-cs2103t-f13-3.github.io/tp/UserGuide.html) or [PlannerMD](https://ay2122s1-cs2103t-t11-3.github.io/tp/UserGuide.html)
- [x] Break command summary table into **Employee Commands**, **Job Commands** and **Other Commands** like [TuitionAddressBook](https://ay2122s1-cs2103t-f13-3.github.io/tp/UserGuide.html)
- [x] Use `💡 Tip` and `❗️ Caution` boxes generously like [NUS Classes](https://ay2122s2-cs2103t-t12-4.github.io/tp/UserGuide.html)
- [x] Add a `User Interface` section which has a labeled UI screenshot (remind Ian to do) Also from [TuitionAddressBook](https://ay2122s1-cs2103t-f13-3.github.io/tp/UserGuide.html) and [Academy Directory](https://ay2122s1-cs2103t-t15-3.github.io/tp/UserGuide.html)
- [x] FAQ questions to answer: [from GoMedic](https://ay2122s1-cs2103t-t15-1.github.io/tp/UserGuide.html)
- [x] Glossaries to credit and adopt: [from LibTask](https://ay2122s2-cs2103t-w14-1.github.io/tp/UserGuide.html) [from TuitionAddressBook](https://ay2122s1-cs2103t-f13-3.github.io/tp/UserGuide.html)

### Nice to have
- [ ] Add links for user to go `back to table of contents` like in TuitionAddressBook after each section
- [ ] Explain our command format like [TuitionAddressBook](https://ay2122s1-cs2103t-f13-3.github.io/tp/UserGuide.html)
![Command format](https://ay2122s1-cs2103t-f13-3.github.io/tp/images/CommandFormat.png)

**Comment by bingsen0806** [comment]
Nice summary!
