### ISSUE TITLE
Duration parsing fails for large numbers without showing exception to user

### ISSUE THREAD

**Issue by ian-from-dover** [AY2122S2-CS2103T-T11-4/tp#211]
steps to reproduce:
1. type in a duration with 17 characters
`job n/work d/12345678901234567`
2. PeopleSoft doesn't respond. Gradle throws Invotaion Target Exception, Arithmetic Exception: long overflow. from ParserUtil line 206.
![Screenshot 2022-04-08 at 12 23 16 PM](https://user-images.githubusercontent.com/62384984/162363549-af37124e-d45c-4dce-94b5-4ef95994a70c.png)

note: the limit is 16 characters if all of them are '9'
![Screenshot 2022-04-08 at 12 21 57 PM](https://user-images.githubusercontent.com/62384984/162363539-39f60b6d-4195-49fe-a899-44909c616998.png)

**Comment by zhongfu** [comment]
no longer an issue, likely closed by #204
