### ISSUE TITLE
Permanent pay multipliers (?) for previously completed `Job`s

### ISSUE THREAD

**Issue by zhongfu** [AY2122S2-CS2103T-T11-4/tp#73]
we probably wouldn't want the pay calculations of past jobs to change when users change tag attributes (or specifically, pay amount)

we might want to consider making it so, e.g.:
- allow for multiple tags with different ids but with the same display name, and only display the latest one
- add change history for multipliers (or whatever) in tags, and calculate pay amount based on job completion date
- store pay amount permanently (but would this prevent us from giving an accurate breakdown of how the pay is calculated?
- ???

**Comment by Spyobird** [comment]
Perhaps we can manage a list of tag prototypes with the updated multipliers. When a tag is assigned for pay calculation, an immutable (deep) clone can be made of the tag. When updating the tags, only the prototype tags in the list are modified.

**Comment by ian-from-dover** [comment]
This has been solved by the `Payment` class and `Assign()` implementation.
