### ISSUE TITLE
Implement timesheet import

### ISSUE THREAD

**Issue by zhongfu** [AY2122S2-CS2103T-T11-4/tp#74]
this depends on how we want to ingest timesheets from employees to keep track of how much they've worked, etc

- decide on a standard format, e.g. csv with certain columns?
- write a parser for this format
- somehow reconcile it w/ existing data

**Comment by ian-from-dover** [comment]
We can base the columns off the existing data needed for jobs and money

**Comment by zhongfu** [comment]
probably too complex for the amount of time we have left
