### ISSUE TITLE
Implement `Payment` class

### ISSUE THREAD

**Issue by thewrik** [AY2122S2-CS2103T-T11-4/tp#93]
- make the `Mark Job As Completed` function generate payment objects, and assign those to the people who did the job
- `Pay()` pays people for all the outstanding payment objects they have, and triggers the generation of the CSV for the person who was paid.

```java
class Payment {
  int amount
  JobID
  [PersonID if it makes sense to have it]
  boolean isCompleted // or you can have these 2 attributes as
  boolean isPaid // child classes which inherit from
  // an `abstract Payment` class instead. your call :)
  // PendingPayment, CompletedPayment
}
```

**Comment by zhongfu** [comment]
picking this one up
