### ISSUE TITLE
`Assign` command `assign j/2 p/1 p/2 p/4`

### ISSUE THREAD

**Issue by ian-from-dover** [AY2122S2-CS2103T-T11-4/tp#96]
based on the 2 lists being displayed
- stores the `Rate basePay` of the persons at the time of assignment of the job
- [so that editing the person's `Rate basePay` after the assignment doesn't change their previous pay]

**Comment by Spyobird** [comment]
Should this use `IDs` or `Index`.

**Comment by ian-from-dover** [comment]
@Spyobird Should use Index, the transient ones we're moving everything user-interaction related to
